version: "3.8"

services:
  jee-duo:
    build: .
    container_name: jee-duo
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
